plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	maven { url "https://download.osgeo.org/webdav/geotools/" }

	// GeoTools
	maven {
		url "https://repo.osgeo.org/repository/release/"
	}

	// JAI
	maven {
		url "https://repo.osgeo.org/repository/thirdparty/"
	}

	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
	implementation 'com.googlecode.json-simple:json-simple:1.1'
	implementation 'org.geotools:gt-main:29.2'
	implementation 'org.geotools:gt-referencing:29.2'
	implementation 'org.geotools:gt-epsg-hsql:29.2'
}


tasks.named('test') {
	useJUnitPlatform()
}
